/*
 * GraphQL for the membership cards page.
 *
 * Deliberately talks to /api/graphql directly rather than going through
 * fe-insuree's action creators. Those are module internals -- fetchInsurees and
 * the projection builders are not part of any published surface -- and binding a
 * local feature to them would make an openIMIS upgrade able to break it silently.
 * The field and filter names below ARE stable: they are the schema, and the same
 * ones fe-insuree's own searcher sends.
 *
 * Every request goes through helpers/csrf.js. openIMIS checks the CSRF token on
 * READ-ONLY QUERIES TOO, which is the opposite of the usual convention -- and
 * assuming otherwise is what made this page fail with a bare 'HTTP_X_CSRFTOKEN',
 * the Python KeyError raised when the header is missing entirely.
 */
import { graphql } from "../helpers/csrf";

/*
 * One box, not three.
 *
 * Three fields asked the operator to classify what they were holding before
 * they could look it up, and the answer was always obvious from the value
 * itself: a name has letters, a number has digits. So the classification is
 * done here instead.
 *
 * The filters themselves are exactly the ones fe-insuree's own searcher sends.
 * Named lookups like lastName_Icontains are generated by graphene-django from
 * the model's filter set, so they are as much part of the schema as the fields
 * -- but they are also the likeliest thing to be renamed upstream, so every one
 * used here is one that appears in the shipped searcher.
 */
const looksLikeNumber = (term) => /\d/.test(term);

/*
 * Punctuation and spacing are noise in an identifier, so a number pasted as
 * "12 3456 7890" or copied out of a spreadsheet with a trailing tab still
 * matches. Names are left exactly as typed -- hyphens and apostrophes belong in
 * them.
 */
const asNumber = (term, maxLength) =>
  term.replace(/[^0-9A-Za-z]/g, "").slice(0, maxLength);

/*
 * Values are interpolated into the query string because that is how openIMIS
 * builds every query it sends (formatPageQuery does the same), so this stays
 * consistent with the rest of the application. Quotes and backslashes are
 * escaped; a name with an apostrophe is ordinary and must not break the query.
 */
const escape = (value) => String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"');

/*
 * Only what a card prints, not INSUREE_FULL_PROJECTION. The full projection
 * pulls the whole family, the health facility and the location tree for every
 * row, which is a lot of payload to fetch and throw away when a batch is a
 * hundred people.
 */
const PROJECTION = `
  uuid
  chfId
  lastName
  otherNames
  dob
  cardIssued
  gender { code }
  photo { photo folder filename }
  currentVillage { name parent { name parent { name } } }
  healthFacility { code name }
  family {
    location { name parent { name parent { name } } }
    headInsuree { chfId lastName otherNames }
  }
`;

/*
 * The backend refuses more than this on the `insurees` connection:
 *
 *   Requesting 200 records on the `insurees` connection exceeds the `first`
 *   limit of 100 records.
 *
 * It is a server-side cap on the relay connection, not a preference, so asking
 * for more fails the whole query rather than returning a shorter list.
 */
export const MAX_CARDS = 100;

/**
 * Insurees matching one search term, which may be an insurance number or a name.
 *
 * A name is searched across BOTH name columns, because someone typing "Somjai"
 * should not have to know whether it is recorded as a given name or a family
 * name. GraphQL filters are combined with AND, so that is two queries -- sent as
 * aliases in a single request rather than two round trips -- and merged here.
 *
 * @param {string} term
 * @param {number} chfIdMaxLength cap applied when the term reads as a number
 * @returns {Promise<Array>} the matching insuree nodes, without duplicates
 */
export async function fetchInsureesForCards(term, chfIdMaxLength = 12, limit = MAX_CARDS) {
  const trimmed = String(term ?? "").trim();
  // Without this an empty box would ask for every insuree in the country.
  if (!trimmed) return [];

  const isNumber = looksLikeNumber(trimmed);
  const value = isNumber ? asNumber(trimmed, chfIdMaxLength) : trimmed;
  if (!value) return [];

  const node = `edges { node { ${PROJECTION} } }`;
  const query = isNumber
    ? `byNumber: insurees(chfId_Istartswith: "${escape(value)}", first: ${limit}) { ${node} }`
    : `byLast: insurees(lastName_Icontains: "${escape(value)}", first: ${limit}) { ${node} }
       byGiven: insurees(otherNames_Icontains: "${escape(value)}", first: ${limit}) { ${node} }`;

  const body = await graphql(`query { ${query} }`);

  /*
   * Someone whose family name and given name both match would otherwise appear
   * twice, and be printed twice. Keyed on uuid, which is the only identifier
   * openIMIS guarantees to be unique -- the insurance number is not.
   */
  const seen = new Map();
  ["byNumber", "byLast", "byGiven"].forEach((alias) => {
    (body?.data?.[alias]?.edges ?? []).forEach((edge) => {
      const insuree = edge?.node;
      if (insuree?.uuid && !seen.has(insuree.uuid)) seen.set(insuree.uuid, insuree);
    });
  });

  return [...seen.values()].slice(0, limit);
}

/*
 * The expiry date is not on the insuree. openIMIS holds validity on the policy,
 * which belongs to the family, so it takes a second query -- and the card in
 * circulation prints one, so it is not optional.
 *
 * Fetched with GraphQL aliases rather than one request per person: a hundred
 * cards would otherwise be a hundred round trips. Batched, because a single
 * request carrying a hundred aliased queries is the other way to make a server
 * unhappy.
 */
const EXPIRY_BATCH = 25;

/**
 * The policy facts a card prints, per insurance number.
 *
 * Two of them, from one query: the expiry date and the product, which is what
 * openIMIS has in place of the entitlement category the social security card
 * prints (ປະເພດຜູ້ເກີດສິດ — civil servant, and so on). A product in openIMIS is
 * the scheme someone is enrolled under, which is the same question.
 *
 * An insuree can hold several policies over the years, so the one that matters
 * is the furthest expiry -- printing an older one would tell a facility the
 * member has lapsed when they have not. The product is read off THAT policy, so
 * the two lines always describe the same cover rather than two different years.
 *
 * Never throws: a card is still worth printing without these, so a failure here
 * leaves those entries absent rather than losing the whole batch.
 *
 * @param {string[]} chfIds
 * @returns {Promise<Object<string, {expiryDate: string, productName: string}>>}
 */
export async function fetchPolicyDetails(chfIds) {
  const details = {};
  const unique = [...new Set(chfIds.filter(Boolean))];

  for (let start = 0; start < unique.length; start += EXPIRY_BATCH) {
    const batch = unique.slice(start, start + EXPIRY_BATCH);
    const query = batch
      .map(
        (chfId, index) =>
          `p${index}: policiesByInsuree(chfId: "${escape(chfId)}", first: 20) {
             edges { node { expiryDate status productName } }
           }`,
      )
      .join("\n");

    try {
      const body = await graphql(`query { ${query} }`);

      batch.forEach((chfId, index) => {
        const policies = (body?.data?.[`p${index}`]?.edges ?? [])
          .map((edge) => edge?.node)
          .filter((node) => node?.expiryDate);
        if (!policies.length) return;
        // Latest expiry wins, and the product comes from the same policy.
        policies.sort((a, b) => String(a.expiryDate).localeCompare(String(b.expiryDate)));
        const latest = policies[policies.length - 1];
        details[chfId] = {
          expiryDate: latest.expiryDate,
          productName: latest.productName || null,
        };
      });
    } catch (error) {
      // eslint-disable-next-line no-console
      console.error("Could not read policy details for a batch:", error);
    }
  }

  return details;
}

/**
 * Where the insuree's photograph can be read from, or null when there is none.
 *
 * Two storage modes, both in use depending on how the deployment was
 * configured: the image inline in the database as base64, or a file under the
 * photos volume. This mirrors getUrl in fe-insuree's InsureeAvatar so a card
 * shows the same picture the profile does.
 */
export function photoUrl(photo) {
  if (photo?.photo) return `data:image/png;base64,${photo.photo}`;
  if (photo?.filename) return `/photos/${photo.folder}/${photo.filename}`;
  return null;
}

/** "Village, District, Region" from whichever of the two location paths exists. */
export function locationLine(insuree) {
  const node = insuree?.currentVillage ?? insuree?.family?.location;
  if (!node) return "";
  return [node.name, node.parent?.name, node.parent?.parent?.name]
    .filter(Boolean)
    .join(", ");
}
