/*
 * GraphQL for the membership cards page.
 *
 * Deliberately talks to /api/graphql directly rather than going through
 * fe-insuree's action creators. Those are module internals -- fetchInsurees and
 * the projection builders are not part of any published surface -- and binding a
 * local feature to them would make an openIMIS upgrade able to break it silently.
 * The field and filter names below ARE stable: they are the schema, and the same
 * ones fe-insuree's own searcher sends.
 *
 * No CSRF token is needed here. The backend checks it in _check_csrf_token,
 * which core/schema.py calls from mutation resolvers only; a query is read-only
 * and is authenticated by the session cookie alone. See
 * src/lao-language/switchLanguage.js for the mutation case, which is not this.
 */
const API = "/api";

/*
 * Exactly the filters fe-insuree's searcher uses. Named lookups like
 * lastName_Icontains are generated by graphene-django from the model's filter
 * set, so they are as much a part of the schema as the fields themselves --
 * but they are also the part most likely to be renamed upstream, so each one
 * used here is one that appears in the shipped searcher.
 */
const FILTERS = {
  chfId: (v) => `chfId_Istartswith: "${escape(v)}"`,
  lastName: (v) => `lastName_Icontains: "${escape(v)}"`,
  otherNames: (v) => `otherNames_Icontains: "${escape(v)}"`,
};

/*
 * Values are interpolated into the query string because that is how openIMIS
 * builds every query it sends (formatPageQuery does the same), so this stays
 * consistent with the rest of the application. Quotes and backslashes are
 * escaped; a name with an apostrophe is ordinary and must not break the query.
 */
const escape = (value) => String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"');

/*
 * Only what a card prints, not INSUREE_FULL_PROJECTION. The full projection
 * pulls the whole family, the health facility and the location tree for every
 * row, which is a lot of payload to fetch and throw away when a batch is a
 * hundred people.
 */
const PROJECTION = `
  uuid
  chfId
  lastName
  otherNames
  dob
  cardIssued
  gender { code }
  photo { photo folder filename }
  currentVillage { name parent { name parent { name } } }
  healthFacility { code name }
  family {
    location { name parent { name parent { name } } }
    headInsuree { chfId lastName otherNames }
  }
`;

/*
 * The backend refuses more than this on the `insurees` connection:
 *
 *   Requesting 200 records on the `insurees` connection exceeds the `first`
 *   limit of 100 records.
 *
 * It is a server-side cap on the relay connection, not a preference, so asking
 * for more fails the whole query rather than returning a shorter list.
 */
export const MAX_CARDS = 100;

/**
 * Insurees matching the given filters, newest first.
 *
 * @param {{chfId?: string, lastName?: string, otherNames?: string}} filters
 * @returns {Promise<Array>} the matching insuree nodes
 */
export async function fetchInsureesForCards(filters, limit = MAX_CARDS) {
  const applied = Object.entries(FILTERS)
    .filter(([name]) => filters[name] && String(filters[name]).trim())
    .map(([name, build]) => build(String(filters[name]).trim()));

  // Without this an empty form would ask for every insuree in the country.
  if (!applied.length) return [];

  const args = [...applied, `first: ${limit}`].join(", ");
  const response = await fetch(`${API}/graphql`, {
    method: "POST",
    credentials: "include",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      query: `query { insurees(${args}) { edges { node { ${PROJECTION} } } } }`,
    }),
  });

  if (!response.ok) throw new Error(`Search failed (${response.status})`);

  const body = await response.json();
  if (body?.errors?.length) throw new Error(body.errors[0].message);

  return (body?.data?.insurees?.edges ?? []).map((edge) => edge.node).filter(Boolean);
}

/*
 * The expiry date is not on the insuree. openIMIS holds validity on the policy,
 * which belongs to the family, so it takes a second query -- and the card in
 * circulation prints one, so it is not optional.
 *
 * Fetched with GraphQL aliases rather than one request per person: a hundred
 * cards would otherwise be a hundred round trips. Batched, because a single
 * request carrying a hundred aliased queries is the other way to make a server
 * unhappy.
 */
const EXPIRY_BATCH = 25;

/**
 * Latest policy expiry date per insurance number.
 *
 * An insuree can hold several policies over the years, so the one that matters
 * on a card is the furthest in the future -- printing an old one would tell a
 * facility the member has lapsed when they have not.
 *
 * Never throws: a card is still worth printing without the date, so a failure
 * here leaves those entries absent rather than losing the whole batch.
 *
 * @param {string[]} chfIds
 * @returns {Promise<Object<string, string>>} insurance number to ISO date
 */
export async function fetchPolicyExpiry(chfIds) {
  const expiry = {};
  const unique = [...new Set(chfIds.filter(Boolean))];

  for (let start = 0; start < unique.length; start += EXPIRY_BATCH) {
    const batch = unique.slice(start, start + EXPIRY_BATCH);
    const query = batch
      .map(
        (chfId, index) =>
          `p${index}: policiesByInsuree(chfId: "${escape(chfId)}", first: 20) {
             edges { node { expiryDate status } }
           }`,
      )
      .join("\n");

    try {
      const response = await fetch(`${API}/graphql`, {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query: `query { ${query} }` }),
      });
      if (!response.ok) continue;
      const body = await response.json();

      batch.forEach((chfId, index) => {
        const edges = body?.data?.[`p${index}`]?.edges ?? [];
        const dates = edges
          .map((edge) => edge?.node?.expiryDate)
          .filter(Boolean)
          .sort();
        if (dates.length) expiry[chfId] = dates[dates.length - 1];
      });
    } catch (error) {
      // eslint-disable-next-line no-console
      console.error("Could not read policy expiry for a batch:", error);
    }
  }

  return expiry;
}

/**
 * Where the insuree's photograph can be read from, or null when there is none.
 *
 * Two storage modes, both in use depending on how the deployment was
 * configured: the image inline in the database as base64, or a file under the
 * photos volume. This mirrors getUrl in fe-insuree's InsureeAvatar so a card
 * shows the same picture the profile does.
 */
export function photoUrl(photo) {
  if (photo?.photo) return `data:image/png;base64,${photo.photo}`;
  if (photo?.filename) return `/photos/${photo.folder}/${photo.filename}`;
  return null;
}

/** "Village, District, Region" from whichever of the two location paths exists. */
export function locationLine(insuree) {
  const node = insuree?.currentVillage ?? insuree?.family?.location;
  if (!node) return "";
  return [node.name, node.parent?.name, node.parent?.parent?.name]
    .filter(Boolean)
    .join(", ");
}
